-- AlterTable
ALTER TABLE "Category" ADD COLUMN     "footballRange" BOOLEAN NOT NULL DEFAULT true;

-- Tracksuits: a category of its own, and sixteen colourways from the WIN WEARS
-- photographs.
--
-- footballRange is false here and for the soccer uniforms, so the customiser's
-- ball types and the Football Collection keep listing only footballs while
-- apparel still appears everywhere a category belongs. The seven tracksuit
-- types stay internal: each product carries one in "usage", which the existing
-- filters and the admin already read, and the website shows a single
-- Tracksuits collection.
--
-- Quote only, no price, no invented fabric or sizing. ON CONFLICT DO NOTHING
-- skips anything already present, so a re-run cannot overwrite an admin edit.

UPDATE "Category" SET "footballRange" = false, "updatedAt" = CURRENT_TIMESTAMP
WHERE "slug" = 'soccer-uniforms' OR "parentId" IS NOT NULL;

INSERT INTO "Category" ("id", "name", "slug", "shortDescription", "description", "image", "displayOrder", "active", "footballRange", "metaTitle", "metaDescription", "updatedAt")
VALUES (
  'cat_tracksuits',
  'Tracksuits',
  'tracksuits',
  'Premium custom tracksuits for football clubs, teams, academies, training, travel and professional sportswear.',
  'Explore premium custom tracksuits manufactured for football clubs, teams, academies, training, travel and professional sportswear.',
  '/assets/img/tracksuits/design-15/1.jpg',
  200,
  true,
  false,
  'Custom Tracksuits Manufacturer | WIN WEARS',
  'Premium custom tracksuits manufactured by WIN WEARS for football clubs, teams, academies, training, travel and professional sportswear.',
  CURRENT_TIMESTAMP
)
ON CONFLICT ("slug") DO NOTHING;

INSERT INTO "Product" ("id", "productName", "slug", "sku", "shortDescription", "usage", "categoryId", "status", "featured", "displayOrder", "customizationAvailable", "quoteOnly", "publishedAt", "updatedAt")
SELECT v.id, 'WIN WEARS Custom Training Tracksuit', v.slug, v.sku, v.colour, 'Training', c."id", 'PUBLISHED'::"ProductStatus", false, v.ord, true, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM (VALUES
  ('prod_ts_01', 'custom-training-tracksuit-white-red-black-ww-ts-01', 'WW-TS-01', 'White · Red · Black', 1),
  ('prod_ts_02', 'custom-training-tracksuit-cream-navy-ww-ts-02', 'WW-TS-02', 'Cream · Navy', 2),
  ('prod_ts_03', 'custom-training-tracksuit-white-royal-blue-ww-ts-03', 'WW-TS-03', 'White · Royal Blue', 3),
  ('prod_ts_04', 'custom-training-tracksuit-grey-navy-ww-ts-04', 'WW-TS-04', 'Grey · Navy', 4),
  ('prod_ts_05', 'custom-training-tracksuit-red-teal-ww-ts-05', 'WW-TS-05', 'Red · Teal', 5),
  ('prod_ts_06', 'custom-training-tracksuit-black-white-ww-ts-06', 'WW-TS-06', 'Black · White', 6),
  ('prod_ts_07', 'custom-training-tracksuit-navy-yellow-ww-ts-07', 'WW-TS-07', 'Navy · Yellow', 7),
  ('prod_ts_08', 'custom-training-tracksuit-purple-white-ww-ts-08', 'WW-TS-08', 'Purple · White', 8),
  ('prod_ts_09', 'custom-training-tracksuit-black-ww-ts-09', 'WW-TS-09', 'Black', 9),
  ('prod_ts_10', 'custom-training-tracksuit-white-blue-ww-ts-10', 'WW-TS-10', 'White · Blue', 10),
  ('prod_ts_11', 'custom-training-tracksuit-navy-blue-yellow-ww-ts-11', 'WW-TS-11', 'Navy · Blue · Yellow', 11),
  ('prod_ts_12', 'custom-training-tracksuit-cream-pink-ww-ts-12', 'WW-TS-12', 'Cream · Pink', 12),
  ('prod_ts_13', 'custom-training-tracksuit-teal-green-ww-ts-13', 'WW-TS-13', 'Teal · Green', 13),
  ('prod_ts_14', 'custom-training-tracksuit-pink-white-ww-ts-14', 'WW-TS-14', 'Pink · White', 14),
  ('prod_ts_15', 'custom-training-tracksuit-black-red-ww-ts-15', 'WW-TS-15', 'Black · Red', 15),
  ('prod_ts_16', 'custom-training-tracksuit-red-black-ww-ts-16', 'WW-TS-16', 'Red · Black', 16)
) AS v(id, slug, sku, colour, ord)
JOIN "Category" c ON c."slug" = 'tracksuits'
ON CONFLICT DO NOTHING;

INSERT INTO "ProductImage" ("id", "productId", "url", "altText", "type", "isPrimary", "displayOrder")
SELECT v.id, p."id", v.url, v.alt, v.kind::"ImageType", v.main, v.ord
FROM (VALUES
  ('img_ts_01_1', 'custom-training-tracksuit-white-red-black-ww-ts-01', '/assets/img/tracksuits/design-01/1.jpg', 'WIN WEARS Custom Training Tracksuit — White · Red · Black', 'MAIN', true, 0),
  ('img_ts_01_2', 'custom-training-tracksuit-white-red-black-ww-ts-01', '/assets/img/tracksuits/design-01/2.jpg', 'WIN WEARS Custom Training Tracksuit — White · Red · Black — view 2', 'GALLERY', false, 1),
  ('img_ts_01_3', 'custom-training-tracksuit-white-red-black-ww-ts-01', '/assets/img/tracksuits/design-01/3.jpg', 'WIN WEARS Custom Training Tracksuit — White · Red · Black — view 3', 'GALLERY', false, 2),
  ('img_ts_01_4', 'custom-training-tracksuit-white-red-black-ww-ts-01', '/assets/img/tracksuits/design-01/4.jpg', 'WIN WEARS Custom Training Tracksuit — White · Red · Black — view 4', 'GALLERY', false, 3),
  ('img_ts_01_5', 'custom-training-tracksuit-white-red-black-ww-ts-01', '/assets/img/tracksuits/design-01/5.jpg', 'WIN WEARS Custom Training Tracksuit — White · Red · Black — view 5', 'GALLERY', false, 4),
  ('img_ts_01_6', 'custom-training-tracksuit-white-red-black-ww-ts-01', '/assets/img/tracksuits/design-01/6.jpg', 'WIN WEARS Custom Training Tracksuit — White · Red · Black — view 6', 'GALLERY', false, 5),
  ('img_ts_01_7', 'custom-training-tracksuit-white-red-black-ww-ts-01', '/assets/img/tracksuits/design-01/7.jpg', 'WIN WEARS Custom Training Tracksuit — White · Red · Black — view 7', 'GALLERY', false, 6),
  ('img_ts_01_8', 'custom-training-tracksuit-white-red-black-ww-ts-01', '/assets/img/tracksuits/design-01/8.jpg', 'WIN WEARS Custom Training Tracksuit — White · Red · Black — view 8', 'GALLERY', false, 7),
  ('img_ts_01_9', 'custom-training-tracksuit-white-red-black-ww-ts-01', '/assets/img/tracksuits/design-01/9.jpg', 'WIN WEARS Custom Training Tracksuit — White · Red · Black — view 9', 'GALLERY', false, 8),
  ('img_ts_02_1', 'custom-training-tracksuit-cream-navy-ww-ts-02', '/assets/img/tracksuits/design-02/1.jpg', 'WIN WEARS Custom Training Tracksuit — Cream · Navy', 'MAIN', true, 0),
  ('img_ts_02_2', 'custom-training-tracksuit-cream-navy-ww-ts-02', '/assets/img/tracksuits/design-02/2.jpg', 'WIN WEARS Custom Training Tracksuit — Cream · Navy — view 2', 'GALLERY', false, 1),
  ('img_ts_02_3', 'custom-training-tracksuit-cream-navy-ww-ts-02', '/assets/img/tracksuits/design-02/3.jpg', 'WIN WEARS Custom Training Tracksuit — Cream · Navy — view 3', 'GALLERY', false, 2),
  ('img_ts_02_4', 'custom-training-tracksuit-cream-navy-ww-ts-02', '/assets/img/tracksuits/design-02/4.jpg', 'WIN WEARS Custom Training Tracksuit — Cream · Navy — view 4', 'GALLERY', false, 3),
  ('img_ts_02_5', 'custom-training-tracksuit-cream-navy-ww-ts-02', '/assets/img/tracksuits/design-02/5.jpg', 'WIN WEARS Custom Training Tracksuit — Cream · Navy — view 5', 'GALLERY', false, 4),
  ('img_ts_02_6', 'custom-training-tracksuit-cream-navy-ww-ts-02', '/assets/img/tracksuits/design-02/6.jpg', 'WIN WEARS Custom Training Tracksuit — Cream · Navy — view 6', 'GALLERY', false, 5),
  ('img_ts_02_7', 'custom-training-tracksuit-cream-navy-ww-ts-02', '/assets/img/tracksuits/design-02/7.jpg', 'WIN WEARS Custom Training Tracksuit — Cream · Navy — view 7', 'GALLERY', false, 6),
  ('img_ts_02_8', 'custom-training-tracksuit-cream-navy-ww-ts-02', '/assets/img/tracksuits/design-02/8.jpg', 'WIN WEARS Custom Training Tracksuit — Cream · Navy — view 8', 'GALLERY', false, 7),
  ('img_ts_02_9', 'custom-training-tracksuit-cream-navy-ww-ts-02', '/assets/img/tracksuits/design-02/9.jpg', 'WIN WEARS Custom Training Tracksuit — Cream · Navy — view 9', 'GALLERY', false, 8),
  ('img_ts_02_10', 'custom-training-tracksuit-cream-navy-ww-ts-02', '/assets/img/tracksuits/design-02/10.jpg', 'WIN WEARS Custom Training Tracksuit — Cream · Navy — view 10', 'GALLERY', false, 9),
  ('img_ts_02_11', 'custom-training-tracksuit-cream-navy-ww-ts-02', '/assets/img/tracksuits/design-02/11.jpg', 'WIN WEARS Custom Training Tracksuit — Cream · Navy — view 11', 'GALLERY', false, 10),
  ('img_ts_02_12', 'custom-training-tracksuit-cream-navy-ww-ts-02', '/assets/img/tracksuits/design-02/12.jpg', 'WIN WEARS Custom Training Tracksuit — Cream · Navy — view 12', 'GALLERY', false, 11),
  ('img_ts_02_13', 'custom-training-tracksuit-cream-navy-ww-ts-02', '/assets/img/tracksuits/design-02/13.jpg', 'WIN WEARS Custom Training Tracksuit — Cream · Navy — view 13', 'GALLERY', false, 12),
  ('img_ts_02_14', 'custom-training-tracksuit-cream-navy-ww-ts-02', '/assets/img/tracksuits/design-02/14.jpg', 'WIN WEARS Custom Training Tracksuit — Cream · Navy — view 14', 'GALLERY', false, 13),
  ('img_ts_02_15', 'custom-training-tracksuit-cream-navy-ww-ts-02', '/assets/img/tracksuits/design-02/15.jpg', 'WIN WEARS Custom Training Tracksuit — Cream · Navy — view 15', 'GALLERY', false, 14),
  ('img_ts_03_1', 'custom-training-tracksuit-white-royal-blue-ww-ts-03', '/assets/img/tracksuits/design-03/1.jpg', 'WIN WEARS Custom Training Tracksuit — White · Royal Blue', 'MAIN', true, 0),
  ('img_ts_03_2', 'custom-training-tracksuit-white-royal-blue-ww-ts-03', '/assets/img/tracksuits/design-03/2.jpg', 'WIN WEARS Custom Training Tracksuit — White · Royal Blue — view 2', 'GALLERY', false, 1),
  ('img_ts_03_3', 'custom-training-tracksuit-white-royal-blue-ww-ts-03', '/assets/img/tracksuits/design-03/3.jpg', 'WIN WEARS Custom Training Tracksuit — White · Royal Blue — view 3', 'GALLERY', false, 2),
  ('img_ts_03_4', 'custom-training-tracksuit-white-royal-blue-ww-ts-03', '/assets/img/tracksuits/design-03/4.jpg', 'WIN WEARS Custom Training Tracksuit — White · Royal Blue — view 4', 'GALLERY', false, 3),
  ('img_ts_03_5', 'custom-training-tracksuit-white-royal-blue-ww-ts-03', '/assets/img/tracksuits/design-03/5.jpg', 'WIN WEARS Custom Training Tracksuit — White · Royal Blue — view 5', 'GALLERY', false, 4),
  ('img_ts_03_6', 'custom-training-tracksuit-white-royal-blue-ww-ts-03', '/assets/img/tracksuits/design-03/6.jpg', 'WIN WEARS Custom Training Tracksuit — White · Royal Blue — view 6', 'GALLERY', false, 5),
  ('img_ts_03_7', 'custom-training-tracksuit-white-royal-blue-ww-ts-03', '/assets/img/tracksuits/design-03/7.jpg', 'WIN WEARS Custom Training Tracksuit — White · Royal Blue — view 7', 'GALLERY', false, 6),
  ('img_ts_03_8', 'custom-training-tracksuit-white-royal-blue-ww-ts-03', '/assets/img/tracksuits/design-03/8.jpg', 'WIN WEARS Custom Training Tracksuit — White · Royal Blue — view 8', 'GALLERY', false, 7),
  ('img_ts_03_9', 'custom-training-tracksuit-white-royal-blue-ww-ts-03', '/assets/img/tracksuits/design-03/9.jpg', 'WIN WEARS Custom Training Tracksuit — White · Royal Blue — view 9', 'GALLERY', false, 8),
  ('img_ts_03_10', 'custom-training-tracksuit-white-royal-blue-ww-ts-03', '/assets/img/tracksuits/design-03/10.jpg', 'WIN WEARS Custom Training Tracksuit — White · Royal Blue — view 10', 'GALLERY', false, 9),
  ('img_ts_03_11', 'custom-training-tracksuit-white-royal-blue-ww-ts-03', '/assets/img/tracksuits/design-03/11.jpg', 'WIN WEARS Custom Training Tracksuit — White · Royal Blue — view 11', 'GALLERY', false, 10),
  ('img_ts_03_12', 'custom-training-tracksuit-white-royal-blue-ww-ts-03', '/assets/img/tracksuits/design-03/12.jpg', 'WIN WEARS Custom Training Tracksuit — White · Royal Blue — view 12', 'GALLERY', false, 11),
  ('img_ts_04_1', 'custom-training-tracksuit-grey-navy-ww-ts-04', '/assets/img/tracksuits/design-04/1.jpg', 'WIN WEARS Custom Training Tracksuit — Grey · Navy', 'MAIN', true, 0),
  ('img_ts_04_2', 'custom-training-tracksuit-grey-navy-ww-ts-04', '/assets/img/tracksuits/design-04/2.jpg', 'WIN WEARS Custom Training Tracksuit — Grey · Navy — view 2', 'GALLERY', false, 1),
  ('img_ts_04_3', 'custom-training-tracksuit-grey-navy-ww-ts-04', '/assets/img/tracksuits/design-04/3.jpg', 'WIN WEARS Custom Training Tracksuit — Grey · Navy — view 3', 'GALLERY', false, 2),
  ('img_ts_04_4', 'custom-training-tracksuit-grey-navy-ww-ts-04', '/assets/img/tracksuits/design-04/4.jpg', 'WIN WEARS Custom Training Tracksuit — Grey · Navy — view 4', 'GALLERY', false, 3),
  ('img_ts_04_5', 'custom-training-tracksuit-grey-navy-ww-ts-04', '/assets/img/tracksuits/design-04/5.jpg', 'WIN WEARS Custom Training Tracksuit — Grey · Navy — view 5', 'GALLERY', false, 4),
  ('img_ts_04_6', 'custom-training-tracksuit-grey-navy-ww-ts-04', '/assets/img/tracksuits/design-04/6.jpg', 'WIN WEARS Custom Training Tracksuit — Grey · Navy — view 6', 'GALLERY', false, 5),
  ('img_ts_04_7', 'custom-training-tracksuit-grey-navy-ww-ts-04', '/assets/img/tracksuits/design-04/7.jpg', 'WIN WEARS Custom Training Tracksuit — Grey · Navy — view 7', 'GALLERY', false, 6),
  ('img_ts_04_8', 'custom-training-tracksuit-grey-navy-ww-ts-04', '/assets/img/tracksuits/design-04/8.jpg', 'WIN WEARS Custom Training Tracksuit — Grey · Navy — view 8', 'GALLERY', false, 7),
  ('img_ts_04_9', 'custom-training-tracksuit-grey-navy-ww-ts-04', '/assets/img/tracksuits/design-04/9.jpg', 'WIN WEARS Custom Training Tracksuit — Grey · Navy — view 9', 'GALLERY', false, 8),
  ('img_ts_04_10', 'custom-training-tracksuit-grey-navy-ww-ts-04', '/assets/img/tracksuits/design-04/10.jpg', 'WIN WEARS Custom Training Tracksuit — Grey · Navy — view 10', 'GALLERY', false, 9),
  ('img_ts_04_11', 'custom-training-tracksuit-grey-navy-ww-ts-04', '/assets/img/tracksuits/design-04/11.jpg', 'WIN WEARS Custom Training Tracksuit — Grey · Navy — view 11', 'GALLERY', false, 10),
  ('img_ts_04_12', 'custom-training-tracksuit-grey-navy-ww-ts-04', '/assets/img/tracksuits/design-04/12.jpg', 'WIN WEARS Custom Training Tracksuit — Grey · Navy — view 12', 'GALLERY', false, 11),
  ('img_ts_04_13', 'custom-training-tracksuit-grey-navy-ww-ts-04', '/assets/img/tracksuits/design-04/13.jpg', 'WIN WEARS Custom Training Tracksuit — Grey · Navy — view 13', 'GALLERY', false, 12),
  ('img_ts_04_14', 'custom-training-tracksuit-grey-navy-ww-ts-04', '/assets/img/tracksuits/design-04/14.jpg', 'WIN WEARS Custom Training Tracksuit — Grey · Navy — view 14', 'GALLERY', false, 13),
  ('img_ts_04_15', 'custom-training-tracksuit-grey-navy-ww-ts-04', '/assets/img/tracksuits/design-04/15.jpg', 'WIN WEARS Custom Training Tracksuit — Grey · Navy — view 15', 'GALLERY', false, 14),
  ('img_ts_05_1', 'custom-training-tracksuit-red-teal-ww-ts-05', '/assets/img/tracksuits/design-05/1.jpg', 'WIN WEARS Custom Training Tracksuit — Red · Teal', 'MAIN', true, 0),
  ('img_ts_05_2', 'custom-training-tracksuit-red-teal-ww-ts-05', '/assets/img/tracksuits/design-05/2.jpg', 'WIN WEARS Custom Training Tracksuit — Red · Teal — view 2', 'GALLERY', false, 1),
  ('img_ts_05_3', 'custom-training-tracksuit-red-teal-ww-ts-05', '/assets/img/tracksuits/design-05/3.jpg', 'WIN WEARS Custom Training Tracksuit — Red · Teal — view 3', 'GALLERY', false, 2),
  ('img_ts_05_4', 'custom-training-tracksuit-red-teal-ww-ts-05', '/assets/img/tracksuits/design-05/4.jpg', 'WIN WEARS Custom Training Tracksuit — Red · Teal — view 4', 'GALLERY', false, 3),
  ('img_ts_05_5', 'custom-training-tracksuit-red-teal-ww-ts-05', '/assets/img/tracksuits/design-05/5.jpg', 'WIN WEARS Custom Training Tracksuit — Red · Teal — view 5', 'GALLERY', false, 4),
  ('img_ts_05_6', 'custom-training-tracksuit-red-teal-ww-ts-05', '/assets/img/tracksuits/design-05/6.jpg', 'WIN WEARS Custom Training Tracksuit — Red · Teal — view 6', 'GALLERY', false, 5),
  ('img_ts_05_7', 'custom-training-tracksuit-red-teal-ww-ts-05', '/assets/img/tracksuits/design-05/7.jpg', 'WIN WEARS Custom Training Tracksuit — Red · Teal — view 7', 'GALLERY', false, 6),
  ('img_ts_05_8', 'custom-training-tracksuit-red-teal-ww-ts-05', '/assets/img/tracksuits/design-05/8.jpg', 'WIN WEARS Custom Training Tracksuit — Red · Teal — view 8', 'GALLERY', false, 7),
  ('img_ts_06_1', 'custom-training-tracksuit-black-white-ww-ts-06', '/assets/img/tracksuits/design-06/1.jpg', 'WIN WEARS Custom Training Tracksuit — Black · White', 'MAIN', true, 0),
  ('img_ts_06_2', 'custom-training-tracksuit-black-white-ww-ts-06', '/assets/img/tracksuits/design-06/2.jpg', 'WIN WEARS Custom Training Tracksuit — Black · White — view 2', 'GALLERY', false, 1),
  ('img_ts_06_3', 'custom-training-tracksuit-black-white-ww-ts-06', '/assets/img/tracksuits/design-06/3.jpg', 'WIN WEARS Custom Training Tracksuit — Black · White — view 3', 'GALLERY', false, 2),
  ('img_ts_06_4', 'custom-training-tracksuit-black-white-ww-ts-06', '/assets/img/tracksuits/design-06/4.jpg', 'WIN WEARS Custom Training Tracksuit — Black · White — view 4', 'GALLERY', false, 3),
  ('img_ts_06_5', 'custom-training-tracksuit-black-white-ww-ts-06', '/assets/img/tracksuits/design-06/5.jpg', 'WIN WEARS Custom Training Tracksuit — Black · White — view 5', 'GALLERY', false, 4),
  ('img_ts_06_6', 'custom-training-tracksuit-black-white-ww-ts-06', '/assets/img/tracksuits/design-06/6.jpg', 'WIN WEARS Custom Training Tracksuit — Black · White — view 6', 'GALLERY', false, 5),
  ('img_ts_06_7', 'custom-training-tracksuit-black-white-ww-ts-06', '/assets/img/tracksuits/design-06/7.jpg', 'WIN WEARS Custom Training Tracksuit — Black · White — view 7', 'GALLERY', false, 6),
  ('img_ts_06_8', 'custom-training-tracksuit-black-white-ww-ts-06', '/assets/img/tracksuits/design-06/8.jpg', 'WIN WEARS Custom Training Tracksuit — Black · White — view 8', 'GALLERY', false, 7),
  ('img_ts_06_9', 'custom-training-tracksuit-black-white-ww-ts-06', '/assets/img/tracksuits/design-06/9.jpg', 'WIN WEARS Custom Training Tracksuit — Black · White — view 9', 'GALLERY', false, 8),
  ('img_ts_06_10', 'custom-training-tracksuit-black-white-ww-ts-06', '/assets/img/tracksuits/design-06/10.jpg', 'WIN WEARS Custom Training Tracksuit — Black · White — view 10', 'GALLERY', false, 9),
  ('img_ts_06_11', 'custom-training-tracksuit-black-white-ww-ts-06', '/assets/img/tracksuits/design-06/11.jpg', 'WIN WEARS Custom Training Tracksuit — Black · White — view 11', 'GALLERY', false, 10),
  ('img_ts_06_12', 'custom-training-tracksuit-black-white-ww-ts-06', '/assets/img/tracksuits/design-06/12.jpg', 'WIN WEARS Custom Training Tracksuit — Black · White — view 12', 'GALLERY', false, 11),
  ('img_ts_06_13', 'custom-training-tracksuit-black-white-ww-ts-06', '/assets/img/tracksuits/design-06/13.jpg', 'WIN WEARS Custom Training Tracksuit — Black · White — view 13', 'GALLERY', false, 12),
  ('img_ts_06_14', 'custom-training-tracksuit-black-white-ww-ts-06', '/assets/img/tracksuits/design-06/14.jpg', 'WIN WEARS Custom Training Tracksuit — Black · White — view 14', 'GALLERY', false, 13),
  ('img_ts_06_15', 'custom-training-tracksuit-black-white-ww-ts-06', '/assets/img/tracksuits/design-06/15.jpg', 'WIN WEARS Custom Training Tracksuit — Black · White — view 15', 'GALLERY', false, 14),
  ('img_ts_07_1', 'custom-training-tracksuit-navy-yellow-ww-ts-07', '/assets/img/tracksuits/design-07/1.jpg', 'WIN WEARS Custom Training Tracksuit — Navy · Yellow', 'MAIN', true, 0),
  ('img_ts_07_2', 'custom-training-tracksuit-navy-yellow-ww-ts-07', '/assets/img/tracksuits/design-07/2.jpg', 'WIN WEARS Custom Training Tracksuit — Navy · Yellow — view 2', 'GALLERY', false, 1),
  ('img_ts_07_3', 'custom-training-tracksuit-navy-yellow-ww-ts-07', '/assets/img/tracksuits/design-07/3.jpg', 'WIN WEARS Custom Training Tracksuit — Navy · Yellow — view 3', 'GALLERY', false, 2),
  ('img_ts_07_4', 'custom-training-tracksuit-navy-yellow-ww-ts-07', '/assets/img/tracksuits/design-07/4.jpg', 'WIN WEARS Custom Training Tracksuit — Navy · Yellow — view 4', 'GALLERY', false, 3),
  ('img_ts_07_5', 'custom-training-tracksuit-navy-yellow-ww-ts-07', '/assets/img/tracksuits/design-07/5.jpg', 'WIN WEARS Custom Training Tracksuit — Navy · Yellow — view 5', 'GALLERY', false, 4),
  ('img_ts_07_6', 'custom-training-tracksuit-navy-yellow-ww-ts-07', '/assets/img/tracksuits/design-07/6.jpg', 'WIN WEARS Custom Training Tracksuit — Navy · Yellow — view 6', 'GALLERY', false, 5),
  ('img_ts_07_7', 'custom-training-tracksuit-navy-yellow-ww-ts-07', '/assets/img/tracksuits/design-07/7.jpg', 'WIN WEARS Custom Training Tracksuit — Navy · Yellow — view 7', 'GALLERY', false, 6),
  ('img_ts_07_8', 'custom-training-tracksuit-navy-yellow-ww-ts-07', '/assets/img/tracksuits/design-07/8.jpg', 'WIN WEARS Custom Training Tracksuit — Navy · Yellow — view 8', 'GALLERY', false, 7),
  ('img_ts_07_9', 'custom-training-tracksuit-navy-yellow-ww-ts-07', '/assets/img/tracksuits/design-07/9.jpg', 'WIN WEARS Custom Training Tracksuit — Navy · Yellow — view 9', 'GALLERY', false, 8),
  ('img_ts_07_10', 'custom-training-tracksuit-navy-yellow-ww-ts-07', '/assets/img/tracksuits/design-07/10.jpg', 'WIN WEARS Custom Training Tracksuit — Navy · Yellow — view 10', 'GALLERY', false, 9),
  ('img_ts_07_11', 'custom-training-tracksuit-navy-yellow-ww-ts-07', '/assets/img/tracksuits/design-07/11.jpg', 'WIN WEARS Custom Training Tracksuit — Navy · Yellow — view 11', 'GALLERY', false, 10),
  ('img_ts_07_12', 'custom-training-tracksuit-navy-yellow-ww-ts-07', '/assets/img/tracksuits/design-07/12.jpg', 'WIN WEARS Custom Training Tracksuit — Navy · Yellow — view 12', 'GALLERY', false, 11),
  ('img_ts_07_13', 'custom-training-tracksuit-navy-yellow-ww-ts-07', '/assets/img/tracksuits/design-07/13.jpg', 'WIN WEARS Custom Training Tracksuit — Navy · Yellow — view 13', 'GALLERY', false, 12),
  ('img_ts_07_14', 'custom-training-tracksuit-navy-yellow-ww-ts-07', '/assets/img/tracksuits/design-07/14.jpg', 'WIN WEARS Custom Training Tracksuit — Navy · Yellow — view 14', 'GALLERY', false, 13),
  ('img_ts_07_15', 'custom-training-tracksuit-navy-yellow-ww-ts-07', '/assets/img/tracksuits/design-07/15.jpg', 'WIN WEARS Custom Training Tracksuit — Navy · Yellow — view 15', 'GALLERY', false, 14),
  ('img_ts_08_1', 'custom-training-tracksuit-purple-white-ww-ts-08', '/assets/img/tracksuits/design-08/1.jpg', 'WIN WEARS Custom Training Tracksuit — Purple · White', 'MAIN', true, 0),
  ('img_ts_08_2', 'custom-training-tracksuit-purple-white-ww-ts-08', '/assets/img/tracksuits/design-08/2.jpg', 'WIN WEARS Custom Training Tracksuit — Purple · White — view 2', 'GALLERY', false, 1),
  ('img_ts_08_3', 'custom-training-tracksuit-purple-white-ww-ts-08', '/assets/img/tracksuits/design-08/3.jpg', 'WIN WEARS Custom Training Tracksuit — Purple · White — view 3', 'GALLERY', false, 2),
  ('img_ts_08_4', 'custom-training-tracksuit-purple-white-ww-ts-08', '/assets/img/tracksuits/design-08/4.jpg', 'WIN WEARS Custom Training Tracksuit — Purple · White — view 4', 'GALLERY', false, 3),
  ('img_ts_08_5', 'custom-training-tracksuit-purple-white-ww-ts-08', '/assets/img/tracksuits/design-08/5.jpg', 'WIN WEARS Custom Training Tracksuit — Purple · White — view 5', 'GALLERY', false, 4),
  ('img_ts_08_6', 'custom-training-tracksuit-purple-white-ww-ts-08', '/assets/img/tracksuits/design-08/6.jpg', 'WIN WEARS Custom Training Tracksuit — Purple · White — view 6', 'GALLERY', false, 5),
  ('img_ts_08_7', 'custom-training-tracksuit-purple-white-ww-ts-08', '/assets/img/tracksuits/design-08/7.jpg', 'WIN WEARS Custom Training Tracksuit — Purple · White — view 7', 'GALLERY', false, 6),
  ('img_ts_08_8', 'custom-training-tracksuit-purple-white-ww-ts-08', '/assets/img/tracksuits/design-08/8.jpg', 'WIN WEARS Custom Training Tracksuit — Purple · White — view 8', 'GALLERY', false, 7),
  ('img_ts_08_9', 'custom-training-tracksuit-purple-white-ww-ts-08', '/assets/img/tracksuits/design-08/9.jpg', 'WIN WEARS Custom Training Tracksuit — Purple · White — view 9', 'GALLERY', false, 8),
  ('img_ts_08_10', 'custom-training-tracksuit-purple-white-ww-ts-08', '/assets/img/tracksuits/design-08/10.jpg', 'WIN WEARS Custom Training Tracksuit — Purple · White — view 10', 'GALLERY', false, 9),
  ('img_ts_08_11', 'custom-training-tracksuit-purple-white-ww-ts-08', '/assets/img/tracksuits/design-08/11.jpg', 'WIN WEARS Custom Training Tracksuit — Purple · White — view 11', 'GALLERY', false, 10),
  ('img_ts_08_12', 'custom-training-tracksuit-purple-white-ww-ts-08', '/assets/img/tracksuits/design-08/12.jpg', 'WIN WEARS Custom Training Tracksuit — Purple · White — view 12', 'GALLERY', false, 11),
  ('img_ts_08_13', 'custom-training-tracksuit-purple-white-ww-ts-08', '/assets/img/tracksuits/design-08/13.jpg', 'WIN WEARS Custom Training Tracksuit — Purple · White — view 13', 'GALLERY', false, 12),
  ('img_ts_08_14', 'custom-training-tracksuit-purple-white-ww-ts-08', '/assets/img/tracksuits/design-08/14.jpg', 'WIN WEARS Custom Training Tracksuit — Purple · White — view 14', 'GALLERY', false, 13),
  ('img_ts_08_15', 'custom-training-tracksuit-purple-white-ww-ts-08', '/assets/img/tracksuits/design-08/15.jpg', 'WIN WEARS Custom Training Tracksuit — Purple · White — view 15', 'GALLERY', false, 14),
  ('img_ts_09_1', 'custom-training-tracksuit-black-ww-ts-09', '/assets/img/tracksuits/design-09/1.jpg', 'WIN WEARS Custom Training Tracksuit — Black', 'MAIN', true, 0),
  ('img_ts_09_2', 'custom-training-tracksuit-black-ww-ts-09', '/assets/img/tracksuits/design-09/2.jpg', 'WIN WEARS Custom Training Tracksuit — Black — view 2', 'GALLERY', false, 1),
  ('img_ts_09_3', 'custom-training-tracksuit-black-ww-ts-09', '/assets/img/tracksuits/design-09/3.jpg', 'WIN WEARS Custom Training Tracksuit — Black — view 3', 'GALLERY', false, 2),
  ('img_ts_09_4', 'custom-training-tracksuit-black-ww-ts-09', '/assets/img/tracksuits/design-09/4.jpg', 'WIN WEARS Custom Training Tracksuit — Black — view 4', 'GALLERY', false, 3),
  ('img_ts_09_5', 'custom-training-tracksuit-black-ww-ts-09', '/assets/img/tracksuits/design-09/5.jpg', 'WIN WEARS Custom Training Tracksuit — Black — view 5', 'GALLERY', false, 4),
  ('img_ts_09_6', 'custom-training-tracksuit-black-ww-ts-09', '/assets/img/tracksuits/design-09/6.jpg', 'WIN WEARS Custom Training Tracksuit — Black — view 6', 'GALLERY', false, 5),
  ('img_ts_09_7', 'custom-training-tracksuit-black-ww-ts-09', '/assets/img/tracksuits/design-09/7.jpg', 'WIN WEARS Custom Training Tracksuit — Black — view 7', 'GALLERY', false, 6),
  ('img_ts_09_8', 'custom-training-tracksuit-black-ww-ts-09', '/assets/img/tracksuits/design-09/8.jpg', 'WIN WEARS Custom Training Tracksuit — Black — view 8', 'GALLERY', false, 7),
  ('img_ts_09_9', 'custom-training-tracksuit-black-ww-ts-09', '/assets/img/tracksuits/design-09/9.jpg', 'WIN WEARS Custom Training Tracksuit — Black — view 9', 'GALLERY', false, 8),
  ('img_ts_09_10', 'custom-training-tracksuit-black-ww-ts-09', '/assets/img/tracksuits/design-09/10.jpg', 'WIN WEARS Custom Training Tracksuit — Black — view 10', 'GALLERY', false, 9),
  ('img_ts_09_11', 'custom-training-tracksuit-black-ww-ts-09', '/assets/img/tracksuits/design-09/11.jpg', 'WIN WEARS Custom Training Tracksuit — Black — view 11', 'GALLERY', false, 10),
  ('img_ts_09_12', 'custom-training-tracksuit-black-ww-ts-09', '/assets/img/tracksuits/design-09/12.jpg', 'WIN WEARS Custom Training Tracksuit — Black — view 12', 'GALLERY', false, 11),
  ('img_ts_10_1', 'custom-training-tracksuit-white-blue-ww-ts-10', '/assets/img/tracksuits/design-10/1.jpg', 'WIN WEARS Custom Training Tracksuit — White · Blue', 'MAIN', true, 0),
  ('img_ts_10_2', 'custom-training-tracksuit-white-blue-ww-ts-10', '/assets/img/tracksuits/design-10/2.jpg', 'WIN WEARS Custom Training Tracksuit — White · Blue — view 2', 'GALLERY', false, 1),
  ('img_ts_10_3', 'custom-training-tracksuit-white-blue-ww-ts-10', '/assets/img/tracksuits/design-10/3.jpg', 'WIN WEARS Custom Training Tracksuit — White · Blue — view 3', 'GALLERY', false, 2),
  ('img_ts_10_4', 'custom-training-tracksuit-white-blue-ww-ts-10', '/assets/img/tracksuits/design-10/4.jpg', 'WIN WEARS Custom Training Tracksuit — White · Blue — view 4', 'GALLERY', false, 3),
  ('img_ts_10_5', 'custom-training-tracksuit-white-blue-ww-ts-10', '/assets/img/tracksuits/design-10/5.jpg', 'WIN WEARS Custom Training Tracksuit — White · Blue — view 5', 'GALLERY', false, 4),
  ('img_ts_10_6', 'custom-training-tracksuit-white-blue-ww-ts-10', '/assets/img/tracksuits/design-10/6.jpg', 'WIN WEARS Custom Training Tracksuit — White · Blue — view 6', 'GALLERY', false, 5),
  ('img_ts_10_7', 'custom-training-tracksuit-white-blue-ww-ts-10', '/assets/img/tracksuits/design-10/7.jpg', 'WIN WEARS Custom Training Tracksuit — White · Blue — view 7', 'GALLERY', false, 6),
  ('img_ts_10_8', 'custom-training-tracksuit-white-blue-ww-ts-10', '/assets/img/tracksuits/design-10/8.jpg', 'WIN WEARS Custom Training Tracksuit — White · Blue — view 8', 'GALLERY', false, 7),
  ('img_ts_10_9', 'custom-training-tracksuit-white-blue-ww-ts-10', '/assets/img/tracksuits/design-10/9.jpg', 'WIN WEARS Custom Training Tracksuit — White · Blue — view 9', 'GALLERY', false, 8),
  ('img_ts_10_10', 'custom-training-tracksuit-white-blue-ww-ts-10', '/assets/img/tracksuits/design-10/10.jpg', 'WIN WEARS Custom Training Tracksuit — White · Blue — view 10', 'GALLERY', false, 9),
  ('img_ts_10_11', 'custom-training-tracksuit-white-blue-ww-ts-10', '/assets/img/tracksuits/design-10/11.jpg', 'WIN WEARS Custom Training Tracksuit — White · Blue — view 11', 'GALLERY', false, 10),
  ('img_ts_10_12', 'custom-training-tracksuit-white-blue-ww-ts-10', '/assets/img/tracksuits/design-10/12.jpg', 'WIN WEARS Custom Training Tracksuit — White · Blue — view 12', 'GALLERY', false, 11),
  ('img_ts_10_13', 'custom-training-tracksuit-white-blue-ww-ts-10', '/assets/img/tracksuits/design-10/13.jpg', 'WIN WEARS Custom Training Tracksuit — White · Blue — view 13', 'GALLERY', false, 12),
  ('img_ts_11_1', 'custom-training-tracksuit-navy-blue-yellow-ww-ts-11', '/assets/img/tracksuits/design-11/1.jpg', 'WIN WEARS Custom Training Tracksuit — Navy · Blue · Yellow', 'MAIN', true, 0),
  ('img_ts_11_2', 'custom-training-tracksuit-navy-blue-yellow-ww-ts-11', '/assets/img/tracksuits/design-11/2.jpg', 'WIN WEARS Custom Training Tracksuit — Navy · Blue · Yellow — view 2', 'GALLERY', false, 1),
  ('img_ts_11_3', 'custom-training-tracksuit-navy-blue-yellow-ww-ts-11', '/assets/img/tracksuits/design-11/3.jpg', 'WIN WEARS Custom Training Tracksuit — Navy · Blue · Yellow — view 3', 'GALLERY', false, 2),
  ('img_ts_11_4', 'custom-training-tracksuit-navy-blue-yellow-ww-ts-11', '/assets/img/tracksuits/design-11/4.jpg', 'WIN WEARS Custom Training Tracksuit — Navy · Blue · Yellow — view 4', 'GALLERY', false, 3),
  ('img_ts_11_5', 'custom-training-tracksuit-navy-blue-yellow-ww-ts-11', '/assets/img/tracksuits/design-11/5.jpg', 'WIN WEARS Custom Training Tracksuit — Navy · Blue · Yellow — view 5', 'GALLERY', false, 4),
  ('img_ts_11_6', 'custom-training-tracksuit-navy-blue-yellow-ww-ts-11', '/assets/img/tracksuits/design-11/6.jpg', 'WIN WEARS Custom Training Tracksuit — Navy · Blue · Yellow — view 6', 'GALLERY', false, 5),
  ('img_ts_11_7', 'custom-training-tracksuit-navy-blue-yellow-ww-ts-11', '/assets/img/tracksuits/design-11/7.jpg', 'WIN WEARS Custom Training Tracksuit — Navy · Blue · Yellow — view 7', 'GALLERY', false, 6),
  ('img_ts_11_8', 'custom-training-tracksuit-navy-blue-yellow-ww-ts-11', '/assets/img/tracksuits/design-11/8.jpg', 'WIN WEARS Custom Training Tracksuit — Navy · Blue · Yellow — view 8', 'GALLERY', false, 7),
  ('img_ts_11_9', 'custom-training-tracksuit-navy-blue-yellow-ww-ts-11', '/assets/img/tracksuits/design-11/9.jpg', 'WIN WEARS Custom Training Tracksuit — Navy · Blue · Yellow — view 9', 'GALLERY', false, 8),
  ('img_ts_11_10', 'custom-training-tracksuit-navy-blue-yellow-ww-ts-11', '/assets/img/tracksuits/design-11/10.jpg', 'WIN WEARS Custom Training Tracksuit — Navy · Blue · Yellow — view 10', 'GALLERY', false, 9),
  ('img_ts_11_11', 'custom-training-tracksuit-navy-blue-yellow-ww-ts-11', '/assets/img/tracksuits/design-11/11.jpg', 'WIN WEARS Custom Training Tracksuit — Navy · Blue · Yellow — view 11', 'GALLERY', false, 10),
  ('img_ts_11_12', 'custom-training-tracksuit-navy-blue-yellow-ww-ts-11', '/assets/img/tracksuits/design-11/12.jpg', 'WIN WEARS Custom Training Tracksuit — Navy · Blue · Yellow — view 12', 'GALLERY', false, 11),
  ('img_ts_11_13', 'custom-training-tracksuit-navy-blue-yellow-ww-ts-11', '/assets/img/tracksuits/design-11/13.jpg', 'WIN WEARS Custom Training Tracksuit — Navy · Blue · Yellow — view 13', 'GALLERY', false, 12),
  ('img_ts_12_1', 'custom-training-tracksuit-cream-pink-ww-ts-12', '/assets/img/tracksuits/design-12/1.jpg', 'WIN WEARS Custom Training Tracksuit — Cream · Pink', 'MAIN', true, 0),
  ('img_ts_12_2', 'custom-training-tracksuit-cream-pink-ww-ts-12', '/assets/img/tracksuits/design-12/2.jpg', 'WIN WEARS Custom Training Tracksuit — Cream · Pink — view 2', 'GALLERY', false, 1),
  ('img_ts_12_3', 'custom-training-tracksuit-cream-pink-ww-ts-12', '/assets/img/tracksuits/design-12/3.jpg', 'WIN WEARS Custom Training Tracksuit — Cream · Pink — view 3', 'GALLERY', false, 2),
  ('img_ts_12_4', 'custom-training-tracksuit-cream-pink-ww-ts-12', '/assets/img/tracksuits/design-12/4.jpg', 'WIN WEARS Custom Training Tracksuit — Cream · Pink — view 4', 'GALLERY', false, 3),
  ('img_ts_12_5', 'custom-training-tracksuit-cream-pink-ww-ts-12', '/assets/img/tracksuits/design-12/5.jpg', 'WIN WEARS Custom Training Tracksuit — Cream · Pink — view 5', 'GALLERY', false, 4),
  ('img_ts_12_6', 'custom-training-tracksuit-cream-pink-ww-ts-12', '/assets/img/tracksuits/design-12/6.jpg', 'WIN WEARS Custom Training Tracksuit — Cream · Pink — view 6', 'GALLERY', false, 5),
  ('img_ts_12_7', 'custom-training-tracksuit-cream-pink-ww-ts-12', '/assets/img/tracksuits/design-12/7.jpg', 'WIN WEARS Custom Training Tracksuit — Cream · Pink — view 7', 'GALLERY', false, 6),
  ('img_ts_12_8', 'custom-training-tracksuit-cream-pink-ww-ts-12', '/assets/img/tracksuits/design-12/8.jpg', 'WIN WEARS Custom Training Tracksuit — Cream · Pink — view 8', 'GALLERY', false, 7),
  ('img_ts_12_9', 'custom-training-tracksuit-cream-pink-ww-ts-12', '/assets/img/tracksuits/design-12/9.jpg', 'WIN WEARS Custom Training Tracksuit — Cream · Pink — view 9', 'GALLERY', false, 8),
  ('img_ts_13_1', 'custom-training-tracksuit-teal-green-ww-ts-13', '/assets/img/tracksuits/design-13/1.jpg', 'WIN WEARS Custom Training Tracksuit — Teal · Green', 'MAIN', true, 0),
  ('img_ts_13_2', 'custom-training-tracksuit-teal-green-ww-ts-13', '/assets/img/tracksuits/design-13/2.jpg', 'WIN WEARS Custom Training Tracksuit — Teal · Green — view 2', 'GALLERY', false, 1),
  ('img_ts_13_3', 'custom-training-tracksuit-teal-green-ww-ts-13', '/assets/img/tracksuits/design-13/3.jpg', 'WIN WEARS Custom Training Tracksuit — Teal · Green — view 3', 'GALLERY', false, 2),
  ('img_ts_13_4', 'custom-training-tracksuit-teal-green-ww-ts-13', '/assets/img/tracksuits/design-13/4.jpg', 'WIN WEARS Custom Training Tracksuit — Teal · Green — view 4', 'GALLERY', false, 3),
  ('img_ts_13_5', 'custom-training-tracksuit-teal-green-ww-ts-13', '/assets/img/tracksuits/design-13/5.jpg', 'WIN WEARS Custom Training Tracksuit — Teal · Green — view 5', 'GALLERY', false, 4),
  ('img_ts_13_6', 'custom-training-tracksuit-teal-green-ww-ts-13', '/assets/img/tracksuits/design-13/6.jpg', 'WIN WEARS Custom Training Tracksuit — Teal · Green — view 6', 'GALLERY', false, 5),
  ('img_ts_13_7', 'custom-training-tracksuit-teal-green-ww-ts-13', '/assets/img/tracksuits/design-13/7.jpg', 'WIN WEARS Custom Training Tracksuit — Teal · Green — view 7', 'GALLERY', false, 6),
  ('img_ts_13_8', 'custom-training-tracksuit-teal-green-ww-ts-13', '/assets/img/tracksuits/design-13/8.jpg', 'WIN WEARS Custom Training Tracksuit — Teal · Green — view 8', 'GALLERY', false, 7),
  ('img_ts_13_9', 'custom-training-tracksuit-teal-green-ww-ts-13', '/assets/img/tracksuits/design-13/9.jpg', 'WIN WEARS Custom Training Tracksuit — Teal · Green — view 9', 'GALLERY', false, 8),
  ('img_ts_13_10', 'custom-training-tracksuit-teal-green-ww-ts-13', '/assets/img/tracksuits/design-13/10.jpg', 'WIN WEARS Custom Training Tracksuit — Teal · Green — view 10', 'GALLERY', false, 9),
  ('img_ts_13_11', 'custom-training-tracksuit-teal-green-ww-ts-13', '/assets/img/tracksuits/design-13/11.jpg', 'WIN WEARS Custom Training Tracksuit — Teal · Green — view 11', 'GALLERY', false, 10),
  ('img_ts_13_12', 'custom-training-tracksuit-teal-green-ww-ts-13', '/assets/img/tracksuits/design-13/12.jpg', 'WIN WEARS Custom Training Tracksuit — Teal · Green — view 12', 'GALLERY', false, 11),
  ('img_ts_13_13', 'custom-training-tracksuit-teal-green-ww-ts-13', '/assets/img/tracksuits/design-13/13.jpg', 'WIN WEARS Custom Training Tracksuit — Teal · Green — view 13', 'GALLERY', false, 12),
  ('img_ts_14_1', 'custom-training-tracksuit-pink-white-ww-ts-14', '/assets/img/tracksuits/design-14/1.jpg', 'WIN WEARS Custom Training Tracksuit — Pink · White', 'MAIN', true, 0),
  ('img_ts_14_2', 'custom-training-tracksuit-pink-white-ww-ts-14', '/assets/img/tracksuits/design-14/2.jpg', 'WIN WEARS Custom Training Tracksuit — Pink · White — view 2', 'GALLERY', false, 1),
  ('img_ts_14_3', 'custom-training-tracksuit-pink-white-ww-ts-14', '/assets/img/tracksuits/design-14/3.jpg', 'WIN WEARS Custom Training Tracksuit — Pink · White — view 3', 'GALLERY', false, 2),
  ('img_ts_14_4', 'custom-training-tracksuit-pink-white-ww-ts-14', '/assets/img/tracksuits/design-14/4.jpg', 'WIN WEARS Custom Training Tracksuit — Pink · White — view 4', 'GALLERY', false, 3),
  ('img_ts_14_5', 'custom-training-tracksuit-pink-white-ww-ts-14', '/assets/img/tracksuits/design-14/5.jpg', 'WIN WEARS Custom Training Tracksuit — Pink · White — view 5', 'GALLERY', false, 4),
  ('img_ts_14_6', 'custom-training-tracksuit-pink-white-ww-ts-14', '/assets/img/tracksuits/design-14/6.jpg', 'WIN WEARS Custom Training Tracksuit — Pink · White — view 6', 'GALLERY', false, 5),
  ('img_ts_14_7', 'custom-training-tracksuit-pink-white-ww-ts-14', '/assets/img/tracksuits/design-14/7.jpg', 'WIN WEARS Custom Training Tracksuit — Pink · White — view 7', 'GALLERY', false, 6),
  ('img_ts_14_8', 'custom-training-tracksuit-pink-white-ww-ts-14', '/assets/img/tracksuits/design-14/8.jpg', 'WIN WEARS Custom Training Tracksuit — Pink · White — view 8', 'GALLERY', false, 7),
  ('img_ts_14_9', 'custom-training-tracksuit-pink-white-ww-ts-14', '/assets/img/tracksuits/design-14/9.jpg', 'WIN WEARS Custom Training Tracksuit — Pink · White — view 9', 'GALLERY', false, 8),
  ('img_ts_14_10', 'custom-training-tracksuit-pink-white-ww-ts-14', '/assets/img/tracksuits/design-14/10.jpg', 'WIN WEARS Custom Training Tracksuit — Pink · White — view 10', 'GALLERY', false, 9),
  ('img_ts_14_11', 'custom-training-tracksuit-pink-white-ww-ts-14', '/assets/img/tracksuits/design-14/11.jpg', 'WIN WEARS Custom Training Tracksuit — Pink · White — view 11', 'GALLERY', false, 10),
  ('img_ts_14_12', 'custom-training-tracksuit-pink-white-ww-ts-14', '/assets/img/tracksuits/design-14/12.jpg', 'WIN WEARS Custom Training Tracksuit — Pink · White — view 12', 'GALLERY', false, 11),
  ('img_ts_14_13', 'custom-training-tracksuit-pink-white-ww-ts-14', '/assets/img/tracksuits/design-14/13.jpg', 'WIN WEARS Custom Training Tracksuit — Pink · White — view 13', 'GALLERY', false, 12),
  ('img_ts_14_14', 'custom-training-tracksuit-pink-white-ww-ts-14', '/assets/img/tracksuits/design-14/14.jpg', 'WIN WEARS Custom Training Tracksuit — Pink · White — view 14', 'GALLERY', false, 13),
  ('img_ts_14_15', 'custom-training-tracksuit-pink-white-ww-ts-14', '/assets/img/tracksuits/design-14/15.jpg', 'WIN WEARS Custom Training Tracksuit — Pink · White — view 15', 'GALLERY', false, 14),
  ('img_ts_15_1', 'custom-training-tracksuit-black-red-ww-ts-15', '/assets/img/tracksuits/design-15/1.jpg', 'WIN WEARS Custom Training Tracksuit — Black · Red', 'MAIN', true, 0),
  ('img_ts_15_2', 'custom-training-tracksuit-black-red-ww-ts-15', '/assets/img/tracksuits/design-15/2.jpg', 'WIN WEARS Custom Training Tracksuit — Black · Red — view 2', 'GALLERY', false, 1),
  ('img_ts_15_3', 'custom-training-tracksuit-black-red-ww-ts-15', '/assets/img/tracksuits/design-15/3.jpg', 'WIN WEARS Custom Training Tracksuit — Black · Red — view 3', 'GALLERY', false, 2),
  ('img_ts_15_4', 'custom-training-tracksuit-black-red-ww-ts-15', '/assets/img/tracksuits/design-15/4.jpg', 'WIN WEARS Custom Training Tracksuit — Black · Red — view 4', 'GALLERY', false, 3),
  ('img_ts_15_5', 'custom-training-tracksuit-black-red-ww-ts-15', '/assets/img/tracksuits/design-15/5.jpg', 'WIN WEARS Custom Training Tracksuit — Black · Red — view 5', 'GALLERY', false, 4),
  ('img_ts_15_6', 'custom-training-tracksuit-black-red-ww-ts-15', '/assets/img/tracksuits/design-15/6.jpg', 'WIN WEARS Custom Training Tracksuit — Black · Red — view 6', 'GALLERY', false, 5),
  ('img_ts_15_7', 'custom-training-tracksuit-black-red-ww-ts-15', '/assets/img/tracksuits/design-15/7.jpg', 'WIN WEARS Custom Training Tracksuit — Black · Red — view 7', 'GALLERY', false, 6),
  ('img_ts_15_8', 'custom-training-tracksuit-black-red-ww-ts-15', '/assets/img/tracksuits/design-15/8.jpg', 'WIN WEARS Custom Training Tracksuit — Black · Red — view 8', 'GALLERY', false, 7),
  ('img_ts_15_9', 'custom-training-tracksuit-black-red-ww-ts-15', '/assets/img/tracksuits/design-15/9.jpg', 'WIN WEARS Custom Training Tracksuit — Black · Red — view 9', 'GALLERY', false, 8),
  ('img_ts_15_10', 'custom-training-tracksuit-black-red-ww-ts-15', '/assets/img/tracksuits/design-15/10.jpg', 'WIN WEARS Custom Training Tracksuit — Black · Red — view 10', 'GALLERY', false, 9),
  ('img_ts_15_11', 'custom-training-tracksuit-black-red-ww-ts-15', '/assets/img/tracksuits/design-15/11.jpg', 'WIN WEARS Custom Training Tracksuit — Black · Red — view 11', 'GALLERY', false, 10),
  ('img_ts_15_12', 'custom-training-tracksuit-black-red-ww-ts-15', '/assets/img/tracksuits/design-15/12.jpg', 'WIN WEARS Custom Training Tracksuit — Black · Red — view 12', 'GALLERY', false, 11),
  ('img_ts_15_13', 'custom-training-tracksuit-black-red-ww-ts-15', '/assets/img/tracksuits/design-15/13.jpg', 'WIN WEARS Custom Training Tracksuit — Black · Red — view 13', 'GALLERY', false, 12),
  ('img_ts_15_14', 'custom-training-tracksuit-black-red-ww-ts-15', '/assets/img/tracksuits/design-15/14.jpg', 'WIN WEARS Custom Training Tracksuit — Black · Red — view 14', 'GALLERY', false, 13),
  ('img_ts_15_15', 'custom-training-tracksuit-black-red-ww-ts-15', '/assets/img/tracksuits/design-15/15.jpg', 'WIN WEARS Custom Training Tracksuit — Black · Red — view 15', 'GALLERY', false, 14),
  ('img_ts_16_1', 'custom-training-tracksuit-red-black-ww-ts-16', '/assets/img/tracksuits/design-16/1.jpg', 'WIN WEARS Custom Training Tracksuit — Red · Black', 'MAIN', true, 0),
  ('img_ts_16_2', 'custom-training-tracksuit-red-black-ww-ts-16', '/assets/img/tracksuits/design-16/2.jpg', 'WIN WEARS Custom Training Tracksuit — Red · Black — view 2', 'GALLERY', false, 1),
  ('img_ts_16_3', 'custom-training-tracksuit-red-black-ww-ts-16', '/assets/img/tracksuits/design-16/3.jpg', 'WIN WEARS Custom Training Tracksuit — Red · Black — view 3', 'GALLERY', false, 2),
  ('img_ts_16_4', 'custom-training-tracksuit-red-black-ww-ts-16', '/assets/img/tracksuits/design-16/4.jpg', 'WIN WEARS Custom Training Tracksuit — Red · Black — view 4', 'GALLERY', false, 3),
  ('img_ts_16_5', 'custom-training-tracksuit-red-black-ww-ts-16', '/assets/img/tracksuits/design-16/5.jpg', 'WIN WEARS Custom Training Tracksuit — Red · Black — view 5', 'GALLERY', false, 4),
  ('img_ts_16_6', 'custom-training-tracksuit-red-black-ww-ts-16', '/assets/img/tracksuits/design-16/6.jpg', 'WIN WEARS Custom Training Tracksuit — Red · Black — view 6', 'GALLERY', false, 5),
  ('img_ts_16_7', 'custom-training-tracksuit-red-black-ww-ts-16', '/assets/img/tracksuits/design-16/7.jpg', 'WIN WEARS Custom Training Tracksuit — Red · Black — view 7', 'GALLERY', false, 6),
  ('img_ts_16_8', 'custom-training-tracksuit-red-black-ww-ts-16', '/assets/img/tracksuits/design-16/8.jpg', 'WIN WEARS Custom Training Tracksuit — Red · Black — view 8', 'GALLERY', false, 7),
  ('img_ts_16_9', 'custom-training-tracksuit-red-black-ww-ts-16', '/assets/img/tracksuits/design-16/9.jpg', 'WIN WEARS Custom Training Tracksuit — Red · Black — view 9', 'GALLERY', false, 8),
  ('img_ts_16_10', 'custom-training-tracksuit-red-black-ww-ts-16', '/assets/img/tracksuits/design-16/10.jpg', 'WIN WEARS Custom Training Tracksuit — Red · Black — view 10', 'GALLERY', false, 9),
  ('img_ts_16_11', 'custom-training-tracksuit-red-black-ww-ts-16', '/assets/img/tracksuits/design-16/11.jpg', 'WIN WEARS Custom Training Tracksuit — Red · Black — view 11', 'GALLERY', false, 10),
  ('img_ts_16_12', 'custom-training-tracksuit-red-black-ww-ts-16', '/assets/img/tracksuits/design-16/12.jpg', 'WIN WEARS Custom Training Tracksuit — Red · Black — view 12', 'GALLERY', false, 11),
  ('img_ts_16_13', 'custom-training-tracksuit-red-black-ww-ts-16', '/assets/img/tracksuits/design-16/13.jpg', 'WIN WEARS Custom Training Tracksuit — Red · Black — view 13', 'GALLERY', false, 12),
  ('img_ts_16_14', 'custom-training-tracksuit-red-black-ww-ts-16', '/assets/img/tracksuits/design-16/14.jpg', 'WIN WEARS Custom Training Tracksuit — Red · Black — view 14', 'GALLERY', false, 13)
) AS v(id, slug, url, alt, kind, main, ord)
JOIN "Product" p ON p."slug" = v.slug
WHERE NOT EXISTS (SELECT 1 FROM "ProductImage" i WHERE i."productId" = p."id" AND i."url" = v.url)
ON CONFLICT DO NOTHING;
